language: java
jdk: oraclejdk8
env:
- TERM=dumb

before_install:
 - chmod +x gradlew

script:
- ./gradlew --info build

deploy:
  provider: releases
  api-key: $API_TOKEN
  file: ./builds/libs/LeBot-1.0.jar
  skip_cleanup: true
  on:
    tags: true
    all_branches: true